name: assignment
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Recommended lints for good coding practices

# For more information on the generic Dart part of this file, see:
# https://dart.dev/tools/pub/pubspec

flutter:
  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true

  # To add assets to your application, add an assets section.
  assets:
    - lib/images/

  # To add custom fonts, use a fonts section.
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700
