// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYztl-D3ybrWya8aG5FdN2gIFsm3SJXrQ',
    appId: '1:716046320878:web:a528a999d7671abaac5fff',
    messagingSenderId: '716046320878',
    projectId: 'login-page-d4dd8',
    authDomain: 'login-page-d4dd8.firebaseapp.com',
    storageBucket: 'login-page-d4dd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HlDqBgiV8Zb1G3JCyoJDWrppcIs5fhE',
    appId: '1:716046320878:android:495931cfe4880549ac5fff',
    messagingSenderId: '716046320878',
    projectId: 'login-page-d4dd8',
    storageBucket: 'login-page-d4dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByslWe78JBNQFa4S2PvYRpQtntff5DYsk',
    appId: '1:716046320878:ios:bfb62b0f36372d80ac5fff',
    messagingSenderId: '716046320878',
    projectId: 'login-page-d4dd8',
    storageBucket: 'login-page-d4dd8.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByslWe78JBNQFa4S2PvYRpQtntff5DYsk',
    appId: '1:716046320878:ios:bfb62b0f36372d80ac5fff',
    messagingSenderId: '716046320878',
    projectId: 'login-page-d4dd8',
    storageBucket: 'login-page-d4dd8.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYztl-D3ybrWya8aG5FdN2gIFsm3SJXrQ',
    appId: '1:716046320878:web:dbc57ad12efd917cac5fff',
    messagingSenderId: '716046320878',
    projectId: 'login-page-d4dd8',
    authDomain: 'login-page-d4dd8.firebaseapp.com',
    storageBucket: 'login-page-d4dd8.appspot.com',
  );

}